# This is a basic workflow to help you get started with Actions

name: comet-core CI

# Controls when the action will run. 
on:
  # Triggers the workflow on all push events and pull request events only for the master branch
  push:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-mypy-${{ hashFiles('setup.py','requirements-dev.txt','constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-mypy-
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      # Add to the dependency
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
      - name: Build python packages to /dist
        run: |
          pip install twine wheel
          python setup.py sdist -d dist bdist_wheel -d dist
      - name: Twine check
        run: |
          python -m twine check dist/*
        shell: bash
      - name: upload
        run: |
          python -m twine upload --skip-existing dist/*
        shell: bash
        env:
          TWINE_REPOSITORY_URL: "https://test.pypi.org"
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
